### ISSUE TITLE
Add a background 

### ISSUE THREAD

**Issue by Ashwani132003** [Ashwani132003/Tic-Tac-Toe#2]

**Comment by Ashwani132003** [comment]
adding background

**Comment by Suyog57** [comment]
is this issue resolved?

**Comment by Ashwani132003** [comment]
No you can go ahead, I will assign it to you Tomorrow 👍

**Comment by daptheHuman** [comment]
assign me

**Comment by theanmolmalik** [comment]
Hi, I am interested to work on this issue. Could you please assign it to me?

**Comment by Ashwani132003** [comment]
@theanmolmalik just do it and create pull request, I will merge it

**Comment by ShrutiUz** [comment]
Hey there! I would like to work on it by adding a better background and improving the UI.

**Comment by Ashwani132003** [comment]
@ShrutiUz  go ahead
